steps:
  # --- 1. Build the Backend Service (ADK) ---
  # We tell docker to build the Dockerfile inside the 'backend' directory
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Backend'
    args:
      [
        'build',
        '-t',
        '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_BACKEND_SERVICE_NAME}:$COMMIT_SHA',
        '.', # '.' refers to the directory specified in 'dir'
      ]
    dir: 'backend' # <--- This is the key: it CAs into the 'backend' folder first

  # --- 2. Build the Frontend UI (CoPilotKit) ---
  # We do the same for the frontend, in parallel
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Frontend'
    args:
      [
        'build',
        '-t',
        '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_FRONTEND_SERVICE_NAME}:$COMMIT_SHA',
        '.',
      ]
    dir: 'frontend' # <--- This tells it to build from the 'frontend' folder

  # --- 3. Push the Backend Image ---
  # This step will wait until 'Build Backend' is done, then push.
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push Backend'
    args: ['push', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_BACKEND_SERVICE_NAME}:$COMMIT_SHA']
    wait_for: ['Build Backend']

  # --- 4. Push the Frontend Image ---
  # This step will wait until 'Build Frontend' is done, then push.
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push Frontend'
    args: ['push', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_FRONTEND_SERVICE_NAME}:$COMMIT_SHA']
    wait_for: ['Build Frontend']

  # --- 5. Deploy the Backend Service ---
  # This step waits for the backend image to be pushed, then deploys it.
  # Note: We keep the backend private by NOT adding '--allow-unauthenticated'.
  - name: 'gcr.io/google-cloud-sdk/gcloud'
    id: 'Deploy Backend'
    args:
      [
        'run',
        'deploy',
        '${_BACKEND_SERVICE_NAME}',
        '--image',
        '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_BACKEND_SERVICE_NAME}:$COMMIT_SHA',
        '--region',
        '${_REGION}',
        '--platform',
        'managed',
      ]
    wait_for: ['Push Backend']

  # --- 6. Deploy the Frontend UI ---
  # This step waits for the frontend image to be pushed, then deploys it.
  # Note: We make the UI public by ADDING '--allow-unauthenticated'.
  - name: 'gcr.io/google-cloud-sdk/gcloud'
    id: 'Deploy Frontend'
    args:
      [
        'run',
        'deploy',
        '${_FRONTEND_SERVICE_NAME}',
        '--image',
        '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_FRONTEND_SERVICE_NAME}:$COMMIT_SHA',
        '--region',
        '${_REGION}',
        '--platform',
        'managed',
        '--allow-unauthenticated', # <-- Makes the website public
      ]
    wait_for: ['Push Frontend']

# --- Tell Cloud Build which images to store ---
images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_BACKEND_SERVICE_NAME}:$COMMIT_SHA'
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_FRONTEND_SERVICE_NAME}:$COMMIT_SHA'

# --- Variables you will set in your Cloud Build Trigger ---
substitutions:
  _BACKEND_SERVICE_NAME: 'deepresearch-backend'
  _FRONTEND_SERVICE_NAME: 'deepresearch-frontend'
  _REGION: 'us-west1'

options:
  logging: CLOUD_LOGGING_ONLY